title: webapps
description: A showcase of web creations like visualizers, kids games, and music tech webapps.
show_downloads: false
google_analytics:
theme: jekyll-theme-midnight
github:
  is_project_page: false
